server:
  port: 8081

spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:postgresql://postgres-service:5432/userservice
    username: postgres
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect